# Generated by Django 4.0.3 on 2022-04-10 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('horror', 'horror'), ('drama', 'drama'), ('self_development', 'self_development')], max_length=256),
        ),
    ]
